import esbuild from "esbuild";
import process from "process";
import { copyFileSync, mkdirSync, existsSync } from "fs";
import { resolve, dirname } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const nodeBuiltins = [
  "assert", "buffer", "child_process", "cluster", "console", "constants",
  "crypto", "dgram", "dns", "domain", "events", "fs", "http", "https",
  "module", "net", "os", "path", "perf_hooks", "process", "punycode",
  "querystring", "readline", "repl", "stream", "string_decoder", "sys",
  "timers", "tls", "tty", "url", "util", "v8", "vm", "wasi", "worker_threads",
  "zlib",
];

// Plugin to copy WASM files to the output directory
const copyWasmPlugin = {
  name: "copy-wasm",
  setup(build) {
    build.onEnd(() => {
      const outDir = dirname(build.initialOptions.outfile || ".");
      const wasmFiles = [
        "node_modules/@jsquash/webp/codec/enc/webp_enc.wasm",
        "node_modules/@jsquash/webp/codec/enc/webp_enc_simd.wasm",
      ];
      for (const src of wasmFiles) {
        const srcPath = resolve(src);
        if (existsSync(srcPath)) {
          const destPath = resolve(outDir, src.split("/").pop());
          copyFileSync(srcPath, destPath);
        }
      }
    });
  },
};

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...nodeBuiltins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  plugins: [copyWasmPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
